IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = N'StajDb')
BEGIN
    CREATE DATABASE [StajDb];
END
GO

USE [StajDb];
GO

CREATE TABLE IF NOT EXISTS TestTable (Id INT PRIMARY KEY IDENTITY, Name NVARCHAR(50));
GO